In [3]:
import pandas as pd
df = pd.read_csv("../data/processed/final_merged_data.csv")
df.head()

,date,state,district,pincode,bio_age_5_17_,bio_age_17__,demo_age_5_17_,demo_age_17__x,age_0_5,age_5_17,age_18_greater,demo_age_5_17_y,demo_age_17__y,bio_age_5_17_y,bio_age_17__y
0,07-11-2025,Haryana,Yamuna Nagar,135002,4.0,6.0,0.0,0.0,0.0,0.0,0.0,2,8,4,6
1,07-11-2025,Haryana,Yamunanagar,135001,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0,6,1,2
2,07-11-2025,Himachal Pradesh,Bilaspur,174004,2.0,2.0,0.0,0.0,0.0,0.0,0.0,1,1,2,2
3,07-11-2025,Himachal Pradesh,Bilaspur,174013,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0,3,3,1
4,07-11-2025,Himachal Pradesh,Bilaspur,174021,21.0,4.0,0.0,0.0,0.0,0.0,0.0,0,5,21,4

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2912682 entries, 0 to 2912681
Data columns (total 15 columns):
 #   Column           Dtype
---  ------           -----
 0   date             object
 1   state            object
 2   district         object
 3   pincode          int64
 4   bio_age_5_17_    float64
 5   bio_age_17__     float64
 6   demo_age_5_17_   float64
 7   demo_age_17__x   float64
 8   age_0_5          float64
 9   age_5_17         float64
 10  age_18_greater   float64
 11  demo_age_5_17_y  int64
 12  demo_age_17__y   int64
 13  bio_age_5_17_y   int64
 14  bio_age_17__y    int64
dtypes: float64(7), int64(5), object(3)
memory usage: 333.3+ MB

In [6]:
df.describe()

,pincode,bio_age_5_17_,bio_age_17__,demo_age_5_17_,demo_age_17__x,age_0_5,age_5_17,age_18_greater,demo_age_5_17_y,demo_age_17__y,bio_age_5_17_y,bio_age_17__y
count,2.912682e+06,2.912682e+06,2.912682e+06,2.912682e+06,2.912682e+06,2.912682e+06,2.912682e+06,2.912682e+06,2.912682e+06,2.912682e+06,2.912682e+06,2.912682e+06
mean,5.202058e+05,5.208537e+00,5.242026e+00,1.112012e+00,1.011284e+01,6.321315e-01,2.736025e-01,1.712545e-02,2.697140e+00,2.451716e+01,1.276900e+01,1.268897e+01
std,2.006062e+05,4.205128e+01,4.593059e+01,1.035383e+01,8.754361e+01,6.941379e+00,3.908551e+00,4.809258e-01,1.543161e+01,1.295040e+02,6.225057e+01,6.775067e+01
min,1.100010e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,3.875700e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00,1.000000e+00,2.000000e+00
50%,5.211350e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,8.000000e+00,4.000000e+00,4.000000e+00
75%,6.896150e+05,2.000000e+00,3.000000e+00,0.000000e+00,5.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,1.900000e+01,1.100000e+01,1.000000e+01
max,8.554560e+05,8.002000e+03,7.625000e+03,2.690000e+03,1.616600e+04,2.688000e+03,1.376000e+03,1.990000e+02,2.690000e+03,1.616600e+04,8.002000e+03,7.625000e+03

In [7]:
df.columns

Index(['date', 'state', 'district', 'pincode', 'bio_age_5_17_', 'bio_age_17__',
       'demo_age_5_17_', 'demo_age_17__x', 'age_0_5', 'age_5_17',
       'age_18_greater', 'demo_age_5_17_y', 'demo_age_17__y', 'bio_age_5_17_y',
       'bio_age_17__y'],
      dtype='object')

In [8]:
df["total_activity"] = (
    df["age_0_5"] + df["age_5_17"] + df["age_18_greater"]
)

print(df["total_activity"].describe())

count    2.912682e+06
mean     9.228594e-01
std      1.072360e+01
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      3.965000e+03
Name: total_activity, dtype: float64

In [9]:
df["total_activity"] = (
    df["demo_age_5_17_y"].fillna(0) +
    df["demo_age_17__y"].fillna(0) +
    df["bio_age_5_17_y"].fillna(0) +
    df["bio_age_17__y"].fillna(0)
)

print(df["total_activity"].describe())

count    2.912682e+06
mean     5.267227e+01
std      2.562346e+02
min      1.000000e+00
25%      9.000000e+00
50%      1.900000e+01
75%      4.400000e+01
max      2.829800e+04
Name: total_activity, dtype: float64

In [10]:
threshold = df["total_activity"].median()

df["low_access"] = df["total_activity"].apply(
    lambda x: 1 if x < threshold else 0
)

In [78]:
from sklearn.preprocessing import LabelEncoder

le_state = LabelEncoder()
le_district = LabelEncoder()

df["state_encoded"] = le_state.fit_transform(df["state"])
df["district_encoded"] = le_district.fit_transform(df["district"])

In [79]:
features = ["state_encoded", "district_encoded"]

X = df[features]
Y = df["low_access"]

In [80]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

In [71]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, Y_train)

RandomForestClassifier()

In [81]:
from sklearn.metrics import accuracy_score

Y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(Y_test, Y_pred))

Accuracy: 0.5150814454704165

In [82]:
low_regions = df[df["low_access"] == 1].copy()
low_regions[["state", "district"]].head()

              state     district
1           Haryana  Yamunanagar
2  Himachal Pradesh     Bilaspur
3  Himachal Pradesh     Bilaspur
5  Himachal Pradesh     Bilaspur
7  Himachal Pradesh     Bilaspur

In [83]:
df["low_access"].value_counts()

low_access
0    1497971
1    1414711
Name: count, dtype: int64

In [84]:
def generate_message(state, district):
    return f"Aadhaar enrollment/update is low in {district}, {state}. Visit nearest Aadhaar center."

low_regions["message"] = low_regions.apply(
    lambda row: generate_message(row["state"], row["district"]),
    axis=1
)

low_regions[["state", "district", "message"]].head()

,state,district,message
1,Haryana,Yamunanagar,Aadhaar enrollment/update is low in Yamunanaga...
2,Himachal Pradesh,Bilaspur,"Aadhaar enrollment/update is low in Bilaspur, ..."
3,Himachal Pradesh,Bilaspur,"Aadhaar enrollment/update is low in Bilaspur, ..."
5,Himachal Pradesh,Bilaspur,"Aadhaar enrollment/update is low in Bilaspur, ..."
7,Himachal Pradesh,Bilaspur,"Aadhaar enrollment/update is low in Bilaspur, ..."

In [85]:
import joblib

joblib.dump(model, "../models/accessibility_model.pkl")

['../models/accessibility_model.pkl']