In [1]:
import pandas as pd
df = pd.read_csv("../data/processed/final_merged_data.csv")
df = df.sample(n=50000, random_state=42)
df.head()

,date,state,district,pincode,bio_age_5_17_x,bio_age_17__x,demo_age_5_17_x,demo_age_17__x,age_0_5,age_5_17,...,bio_age_17__y,total_activity,risk_level,low_access,state_encoded,district_encoded,confidence,future_activity,future_risk,risk_score
33553,25-10-2025,Uttar Pradesh,Sitapur,261201,31.0,18.0,0.0,0.0,0.0,0.0,...,18,109,High Risk,0,40,740,0.187270,65.0,0,0.0
9427,26-10-2025,Madhya Pradesh,Chhindwara,480331,0.0,0.0,0.0,10.0,0.0,0.0,...,12,25,High Risk,0,24,155,0.312336,5.0,1,0.0
199,29-12-2025,Bihar,Siwan,841232,33.0,18.0,0.0,0.0,0.0,0.0,...,18,93,High Risk,0,5,742,0.205798,20.0,0,0.0
12447,01-06-2025,Andhra Pradesh,Srikakulam,532443,0.0,0.0,66.0,171.0,0.0,0.0,...,121,561,High Risk,0,2,768,0.536766,35.0,0,0.0
39489,20-09-2025,Andhra Pradesh,Nalgonda,508373,0.0,11.0,0.0,0.0,0.0,0.0,...,11,19,High Risk,0,2,549,0.860704,10.0,1,0.0

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50000 entries, 33553 to 15795
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              50000 non-null  object
 1   state             50000 non-null  object
 2   district          50000 non-null  object
 3   pincode           50000 non-null  int64
 4   bio_age_5_17_x    50000 non-null  float64
 5   bio_age_17__x     50000 non-null  float64
 6   demo_age_5_17_x   50000 non-null  float64
 7   demo_age_17__x    50000 non-null  float64
 8   age_0_5           50000 non-null  float64
 9   age_5_17          50000 non-null  float64
 10  age_18_greater    50000 non-null  float64
 11  demo_age_5_17_y   50000 non-null  int64
 12  demo_age_17__y    50000 non-null  int64
 13  bio_age_5_17_y    50000 non-null  int64
 14  bio_age_17__y     50000 non-null  int64
 15  total_activity    50000 non-null  int64
 16  risk_level        50000 non-null  object
 17  low_access        50000 non-null  int64
 18  state_encoded     50000 non-null  int64
 19  district_encoded  50000 non-null  int64
 20  confidence        50000 non-null  float64
 21  future_activity   50000 non-null  float64
 22  future_risk       50000 non-null  int64
 23  risk_score        50000 non-null  float64
dtypes: float64(10), int64(10), object(4)
memory usage: 9.5+ MB

In [3]:
df.describe()

,pincode,bio_age_5_17_x,bio_age_17__x,demo_age_5_17_x,demo_age_17__x,age_0_5,age_5_17,age_18_greater,demo_age_5_17_y,demo_age_17__y,bio_age_5_17_y,bio_age_17__y,total_activity,low_access,state_encoded,district_encoded,confidence,future_activity,future_risk,risk_score
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,521170.226620,4.949460,5.148700,1.074820,10.087280,0.643480,0.262380,0.015380,2.574500,23.727820,12.619220,12.712240,51.633780,0.487700,24.994960,436.251520,0.487399,51.633960,0.504540,0.487700
std,200396.894572,35.003644,43.299026,9.197032,91.404312,7.554323,2.559544,0.378347,13.731449,118.204555,60.868651,67.494483,241.504998,0.499854,13.199278,258.377165,0.195268,241.504971,0.499984,0.499854
min,110001.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.028570,1.000000,0.000000,0.000000
25%,388305.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,1.000000,2.000000,9.000000,0.000000,16.000000,211.000000,0.310540,9.000000,0.000000,0.000000
50%,521163.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,8.000000,4.000000,4.000000,19.000000,0.000000,25.000000,436.000000,0.485688,19.000000,1.000000,0.000000
75%,689681.250000,2.000000,3.000000,0.000000,5.000000,0.000000,0.000000,0.000000,2.000000,19.000000,11.000000,10.000000,44.000000,1.000000,37.000000,653.000000,0.623587,44.000000,1.000000,1.000000
max,855117.000000,3366.000000,3180.000000,888.000000,10497.000000,1293.000000,400.000000,30.000000,957.000000,10497.000000,3556.000000,4266.000000,18070.000000,1.000000,44.000000,879.000000,0.997949,18070.000000,1.000000,1.000000

In [4]:
df.columns

Index(['date', 'state', 'district', 'pincode', 'bio_age_5_17_x',
       'bio_age_17__x', 'demo_age_5_17_x', 'demo_age_17__x', 'age_0_5',
       'age_5_17', 'age_18_greater', 'demo_age_5_17_y', 'demo_age_17__y',
       'bio_age_5_17_y', 'bio_age_17__y', 'total_activity', 'risk_level',
       'low_access', 'state_encoded', 'district_encoded', 'confidence',
       'future_activity', 'future_risk', 'risk_score'],
      dtype='object')

In [5]:
df["total_activity"] = (
    df["age_0_5"] + df["age_5_17"] + df["age_18_greater"]
)

print(df["total_activity"].describe())

count    50000.000000
mean         0.921240
std         10.143324
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max       1717.000000
Name: total_activity, dtype: float64

In [6]:
df["total_activity"] = (
    df["demo_age_5_17_y"].fillna(0) +
    df["demo_age_17__y"].fillna(0) +
    df["bio_age_5_17_y"].fillna(0) +
    df["bio_age_17__y"].fillna(0)
)

print(df["total_activity"].describe())

count    50000.000000
mean        51.633780
std        241.504998
min          1.000000
25%          9.000000
50%         19.000000
75%         44.000000
max      18070.000000
Name: total_activity, dtype: float64

In [7]:
threshold = df["total_activity"].median()

df["low_access"] = df["total_activity"].apply(
    lambda x: 1 if x < threshold else 0
)

In [8]:
from sklearn.preprocessing import LabelEncoder

le_state = LabelEncoder()
le_district = LabelEncoder()

df["state_encoded"] = le_state.fit_transform(df["state"])
df["district_encoded"] = le_district.fit_transform(df["district"])

In [9]:
features = ["state_encoded", "district_encoded"]

X = df[features]
Y = df["low_access"]

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

In [11]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=50, max_depth=10)
model.fit(X_train, Y_train)

RandomForestClassifier(max_depth=10, n_estimators=50)

In [12]:
from sklearn.metrics import accuracy_score

Y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(Y_test, Y_pred))

Accuracy: 0.6943

In [13]:
low_regions = df[df["low_access"] == 1].copy()
low_regions[["state", "district"]].head()

                state            district
49498  Madhya Pradesh        Narmadapuram
4144           Kerala  Thiruvananthapuram
43106       Karnataka            Tumakuru
6188           Kerala              Kollam
1414        Telangana          Peddapalli

In [14]:
df["low_access"].value_counts()

low_access
0    25615
1    24385
Name: count, dtype: int64

In [15]:
def generate_message(state, district):
    return f"Aadhaar enrollment/update is low in {district}, {state}. Visit nearest Aadhaar center."

low_regions["message"] = low_regions.apply(
    lambda row: generate_message(row["state"], row["district"]),
    axis=1
)

low_regions[["state", "district", "message"]].head()

,state,district,message
49498,Madhya Pradesh,Narmadapuram,Aadhaar enrollment/update is low in Narmadapur...
4144,Kerala,Thiruvananthapuram,Aadhaar enrollment/update is low in Thiruvanan...
43106,Karnataka,Tumakuru,"Aadhaar enrollment/update is low in Tumakuru, ..."
6188,Kerala,Kollam,"Aadhaar enrollment/update is low in Kollam, Ke..."
1414,Telangana,Peddapalli,Aadhaar enrollment/update is low in Peddapalli...

In [16]:
# Recreate X after sampling
X = df[["state_encoded", "district_encoded", "total_activity"]]

# -------------------------------
# CONFIDENCE SCORE
# -------------------------------
df["confidence"] = model.predict_proba(df[["state_encoded", "district_encoded"]])[:, 1]

# -------------------------------
# FUTURE PREDICTION
# -------------------------------
df["future_activity"] = df["total_activity"].shift(-1)
df["future_activity"] = df["future_activity"].fillna(df["future_activity"].median())

future_threshold = df["future_activity"].median()

df["future_risk"] = df["future_activity"].apply(
    lambda x: 1 if x <= future_threshold else 0
)

# -------------------------------
# RISK SCORE
# -------------------------------
df["risk_score"] = (
    df["low_access"] * 0.6 +
    (df["total_activity"] < threshold) * 0.4
)

In [17]:
# -------------------------------
# FEATURE IMPORTANCE 
# -------------------------------
import pandas as pd

importance = model.feature_importances_

feature_importance_df = pd.DataFrame({
    "feature": ["state_encoded", "district_encoded"],
    "importance": importance
}).sort_values(by="importance", ascending=False)

print(feature_importance_df)

            feature  importance
0     state_encoded    0.593574
1  district_encoded    0.406426

In [18]:
df.to_csv("../data/processed/final_merged_data.csv", index=False)

In [19]:
import joblib

joblib.dump(model, "../models/accessibility_model.pkl")

['../models/accessibility_model.pkl']